#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# Generate THIRD-PARTY-LICENSES.md by concatenating the LICENSE text of every
# resolved SPM dependency. Required to satisfy the attribution clauses of the
# MIT / Apache-2.0 / BSD licenses when we distribute the linked binary (the DMG).
#
# Source of truth for *which* deps: build/SourcePackages/checkouts (populated by
# `make release`/`make build`). SPDX ids come from Scripts/licenses.json.
# ---------------------------------------------------------------------------

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CK="${ROOT}/build/SourcePackages/checkouts"
ALT_CK="${HOME}/Library/Developer/Xcode/DerivedData"
ALLOWLIST="${ROOT}/Scripts/licenses.json"
OUT="${ROOT}/THIRD-PARTY-LICENSES.md"

if [[ ! -d "${CK}" ]]; then
    # Fall back to the most recent DerivedData checkout dir.
    CK=$(find "${ALT_CK}" -type d -path "*Scribe-*/SourcePackages/checkouts" 2>/dev/null | head -1)
fi

if [[ -z "${CK:-}" || ! -d "${CK}" ]]; then
    echo "error: no SPM checkouts found — run 'make release' first." >&2
    exit 1
fi

echo "Generating ${OUT} from ${CK}"

{
    echo "# Third-Party Licenses"
    echo
    echo "Scribe (MIT, © 2026 Dan Brodie) statically links the open-source packages below."
    echo "Their licenses (MIT / Apache-2.0 / BSD-class) require that we reproduce their notices"
    echo "in distributions; the full text of each is included here."
    echo
    echo "Generated by \`Scripts/generate-attributions.sh\` — do not edit by hand."
    echo
    echo "Model weights are downloaded at runtime, not bundled: **Google Gemma 4** (Apache-2.0) and"
    echo "**NVIDIA Parakeet** via FluidAudio (permissive). See their model cards for terms."
    echo
    echo "---"
    echo
} > "${OUT}"

for dir in $(ls "${CK}" | sort -f); do
    path="${CK}/${dir}"
    [[ -d "${path}" ]] || continue
    lic=$(ls "${path}" 2>/dev/null | grep -iE "^license|^licence|^copying|^notice" | head -1 || true)
    spdx=$(python3 -c "import json,sys; d=json.load(open('${ALLOWLIST}'))['dependencies']; print(d.get('${dir}'.lower(),'(unclassified)'))" 2>/dev/null || echo "(unknown)")
    {
        echo "## ${dir}"
        echo
        echo "- SPDX: \`${spdx}\`"
        if [[ -n "${lic}" ]]; then
            echo
            echo '```'
            cat "${path}/${lic}"
            echo '```'
        else
            echo "- (no LICENSE file found in checkout)"
        fi
        echo
        echo "---"
        echo
    } >> "${OUT}"
done

count=$(grep -c '^## ' "${OUT}")
echo "Wrote ${OUT} (${count} dependencies)"
